version: '3.7'

networks:
  network:
    driver: bridge

# NESTJS
services:
  nestjs:
    container_name: nestjs
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - network
    volumes:
      - ./backend:/backend

  # VUE
  vue:
    container_name: vue
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - network
    volumes:
      - ./frontend:/frontend
    depends_on:
      - nestjs

