version: '3.7'

networks:
  network:
    driver: bridge

# VOLUMES
volumes:
  vol_backend:
    driver_opts:
      device: ./backend
      o: bind
      type: none
  vol_frontend:
    driver_opts:
      device: ./frontend
      o: bind
      type: none

#NESTJS
services:
  nestjs:
    container_name: nestjs
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - network
    volumes:
      - vol_backend:/backend

  vue:
    container_name: vue
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - network
    volumes:
      - vol_frontend:/frontend
    depends_on:
      - nestjs
