version: '3.7'

networks:
  network:
    driver: bridge

#NESTJS
services:
  nestjs:
    container_name: nestjs
    image: node:lts
    command: bash -c "cd /backend && npm cache clean -f && npm install && sleep 10 && npx prisma migrate dev --name update && npm run start:dev"
    ports:
      - "3000:3000"
      - "9229:9229" #debugging port ?
    restart: always
    networks:
      - network
    volumes:
      - ./backend:/backend

  vue:
    container_name: vue
    image: node:21-alpine3.17
    command: sh -c "cd /frontend && npm install && npm run serve"
    ports:
      - "8080:8080"
    networks:
      - network
    volumes:
      - ./frontend:/frontend
    depends_on:
      - nestjs

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON_URL: http://localhost:3000/api-docs-json
      BASE_URL: /swagger
      PORT: 8080
    ports:
      - "9090:8080"
    restart: always
    networks:
      - network
    depends_on:
      - nestjs

# #POSTGRESQL
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine3.17
    env_file: .env
    restart: always
    networks:
      - network
    volumes:
      - ./data/sql:/var/lib/postgresql/data

# #PHPMYADMIN
  phppgadmin:
    container_name: phppgadmin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    restart: always
    networks:
      - network
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
