version: '3.7'

networks:
  network:
    driver: bridge

#NESTJS
services:
  nestjs:
    container_name: nestjs
    image: node:lts
    env_file: .env
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - network
    volumes:
      - ./backend:/backend
      - ./frontend/public/avatars:/backend/avatars
      - ./certificate.key/:/certificates/certificate.key
      - ./certificate.cert/:/certificates/certificate.cert

#VUE
  vue:
    container_name: vue
    image: node:21-alpine3.17
    env_file: .env
    command: sh -c "cd /frontend && npm config set loglevel error -g && npm install --no-fund --no-update-notifier -g @vue/cli && npm install && npm run serve"
    ports:
      - "8080:8080"
    networks:
      - network
    volumes:
      - ./frontend:/frontend
      - ./certificate.key/:/certificates/certificate.key
      - ./certificate.cert/:/certificates/certificate.cert
    depends_on:
      - nestjs

# #POSTGRESQL
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine3.17
    env_file: .env
    restart: always
    networks:
      - network
    volumes:
      - ./data/sql:/var/lib/postgresql/data

# # #PHPPGADMIN
#   phppgadmin:
#     container_name: phppgadmin
#     image: dpage/pgadmin4
#     env_file: .env
#     ports:
#       - "5050:80"
#     restart: always
#     networks:
#       - network
#     volumes:
#       - ./data/pgadmin:/var/lib/pgadmin
#     depends_on:
#       - postgresql
