version: '3.9'

networks:
  network:
    driver: bridge

# VOLUMES
volumes:
  vol_backend:
    driver_opts:
      device: ./backend
      o: bind
      type: none
  vol_frontend:
    driver_opts:
      device: ./frontend
      o: bind
      type: none

#NESTJS
services:
  nestjs:
    container_name: nestjs
    image: node:latest
    command: bash -c "npm install -g npm@10.2.0 @nestjs/cli && npm install && nest start --watch"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - network
    volumes:
      - vol_backend:/backend
    working_dir: /backend

  vue:
    container_name: vue
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - network
    volumes:
      - vol_frontend:/frontend
    depends_on:
      - nestjs
