<template>
  <table class="centered">
    <thead>
      <td>
        <div class="image_profile"><img src="avatar/3.png" alt="Avatar" /></div>
      </td>
      <td>
        <p>Nickname</p>
        <p>Email</p>
        <p>Registered since</p>
        <p>Date</p>
      </td>
    </thead>
    <!-- the table row has to be generated by vue with data from the backend -->
    <tr v-for="match in userHistory" :key="match.id">
      <td>
        <div class="image_history">
          <img :src="getAvatarSrc(match.leftUser.avatar)" alt="Avatar" />
        </div>
        <div>{{ match.leftUser.nick }}</div>
      </td>
      <td>
        <div>
          <div>{{ match.left_user_score }}</div>
          <b>:</b>
          <div>{{ match.right_user_score }}</div>
        </div>
      </td>
      <td>
        <div>{{ match.rightUser.nick }}</div>
        <div class="image_history">
          <img :src="getAvatarSrc(match.rightUser.avatar)" alt="Avatar" />
        </div>
      </td>
    </tr>
  </table>
</template>

<script>
export default {
  data() {
    return {
      userHistory: null,
    };
  },
  mounted() {
    // Make a call to your NestJS backend when the component is mounted
    this.fetchUserHistory();
  },
  methods: {
    async fetchUserHistory() {
      try {
        // Replace 'YOUR_BACKEND_URL' with the actual URL of your NestJS backend
        const response = await fetch(
          `https://${process.env.VUE_APP_BACKEND_IP}:3000/stats/user`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              userId: localStorage.getItem("userId"),
            }),
          },
        );

        if (response.ok) {
          const data = await response.json();
          this.userHistory = data;
          // Handle the user history data as needed
        } else {
          console.error("Failed to fetch user history");
        }
      } catch (error) {
        console.error("Error fetching user history:", error);
      }
    },
    getAvatarSrc(avatar) {
      // Adjust the path as needed based on your avatar structure
      return `avatar/${avatar}.png`;
    },
  },
};
</script>

<style>
.image_history {
  width: 32px;
  height: 32px;
  overflow: hidden;
  display: inline-block;
  position: relative;
}

.image_history img {
  width: 100%;
  height: 100%;
  object-fit: cover; /* This property ensures the image fills the 32x32 container without distorting its aspect ratio */
  transform: scale(
    1
  ); /* Scale the image down to fit within the 32x32 container */
}

/* Center the user text */
.image_history + div {
  display: inline-block;
  vertical-align: middle;
  margin-left: 8px; /* Adjust the margin as needed */
}

/* Bold style for user text */
.image_history + div b {
  font-weight: bold;
}
.image_profile {
  width: 64px;
  height: 64px;
  overflow: hidden;
  display: inline-block;
  position: relative;
}

.image_profile img {
  width: 100%;
  height: 100%;
  object-fit: cover; /* This property ensures the image fills the 32x32 container without distorting its aspect ratio */
  transform: scale(
    1
  ); /* Scale the image down to fit within the 32x32 container */
}
</style>
