<template>
  <div>
    <table class="centered">
      <thead>
        <tr v-if="userProfil">
          <th colspan="2">
            <div class="image_profile">
              <img :src="getAvatarSrc(userProfil.avatar)" alt="Avatar" />
            </div>
          </th>
          <th colspan="2">
            <p>{{ userProfil.nick }}</p>
            <p>{{ userProfil.email }}</p>
            <p>Registered since</p>
            <p>{{ userProfil.createdAt }}</p>
          </th>
        </tr>
      </thead>
      <!-- the table row has to be generated by vue with data from the backend -->
      <tbody v-if="userHistory">
        <tr v-for="match in userHistory" :key="match.id">
          <td>
            <div class="image_history">
              <img :src="getAvatarSrc(match.leftUser.avatar)" alt="Avatar" />
            </div>
          </td>
          <td>
            {{ match.leftUser.nick }}
          </td>
          <td>
            {{ match.left_user_score }}
          </td>
          <td>
            <b>:</b>
          </td>
          <td>
            {{ match.right_user_score }}
          </td>
          <td>
            {{ match.rightUser.nick }}
          </td>
          <td>
            <div class="image_history">
              <img :src="getAvatarSrc(match.rightUser.avatar)" alt="Avatar" />
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <FriendList />
</template>

<script>
import FriendList from "@/components/FriendList.vue";

export default {
  components: { FriendList },
  data() {
    return {
      userProfil: null,
      userHistory: null,
    };
  },
  mounted() {
    // Make a call to your NestJS backend when the component is mounted
    this.fetchUserHistory();
  },
  methods: {
    async fetchUserHistory() {
      try {
        // Replace 'YOUR_BACKEND_URL' with the actual URL of your NestJS backend
        const response = await fetch(
          `https://${process.env.VUE_APP_BACKEND_IP}:3000/data/userstats`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              userId: localStorage.getItem("userId"),
            }),
          },
        );

        if (response.ok) {
          const responseData = await response.json();
          this.userProfil = responseData.userProfil;
          this.userHistory = responseData.userHistory;
          console.log(this.data);
          // Handle the user history data as needed
        } else {
          console.error("Failed to fetch user history");
        }
      } catch (error) {
        console.error("Error fetching user history:", error);
      }
    },
    getAvatarSrc(avatar) {
      // Adjust the path as needed based on your avatar structure
      return `https://${process.env.VUE_APP_BACKEND_IP}:8080/avatar/${avatar}.png`;
    },
  },
};
</script>

<style>
.image_history {
  width: 48px;
  height: 48px;
  overflow: hidden;
  display: inline-block;
  position: relative;
}

.image_history img {
  width: 100%;
  height: 100%;
  object-fit: cover; /* This property ensures the image fills the 32x32 container without distorting its aspect ratio */
  transform: scale(
    1
  ); /* Scale the image down to fit within the 32x32 container */
}

/* Center the user text */
.image_history + div {
  display: inline-block;
  vertical-align: middle;
  margin-left: 8px; /* Adjust the margin as needed */
}

/* Bold style for user text */
.image_history + div b {
  font-weight: bold;
}
.image_profile {
  width: 128px;
  height: 128px;
  overflow: hidden;
  display: inline-block;
  position: relative;
}

.image_profile img {
  width: 100%;
  height: 100%;
  object-fit: cover; /* This property ensures the image fills the 32x32 container without distorting its aspect ratio */
  transform: scale(
    1
  ); /* Scale the image down to fit within the 32x32 container */
}
</style>
