<template>
  <table class="centered">
    <thead>
      <td>
        <div class="image_profile"><img src="avatar/3.png" alt="Avatar" /></div>
      </td>
      <td>
        <p>Nickname</p>
        <p>Email</p>
        <p>Registered since</p>
        <p>Date</p>
      </td>
    </thead>
    <!-- the table row has to be generated by vue with data from the backend -->
    <tr>
      <td>
        <div class="image_history"><img src="avatar/4.png" alt="Avatar" /></div>
        <div>User1</div>
      </td>
      <td>
        <div>
          <div>11</div>
          <b>:</b>
          <div>8</div>
        </div>
      </td>
      <td>
        <div>User2</div>
        <div class="image_history"><img src="avatar/3.png" alt="Avatar" /></div>
      </td>
    </tr>
    <!-- following row just to show the profil site -->
    <tr>
      <td>
        <div class="image_history"><img src="avatar/3.png" alt="Avatar" /></div>
        <div>User2</div>
      </td>
      <td>
        <div>
          <div>11</div>
          <b>:</b>
          <div>8</div>
        </div>
      </td>
      <td>
        <div>User8</div>
        <div class="image_history"><img src="avatar/7.png" alt="Avatar" /></div>
      </td>
    </tr>
  </table>
</template>

<script></script>

<style>
.image_history {
  width: 32px;
  height: 32px;
  overflow: hidden;
  display: inline-block;
  position: relative;
}

.image_history img {
  width: 100%;
  height: 100%;
  object-fit: cover; /* This property ensures the image fills the 32x32 container without distorting its aspect ratio */
  transform: scale(
    1
  ); /* Scale the image down to fit within the 32x32 container */
}

/* Center the user text */
.image_history + div {
  display: inline-block;
  vertical-align: middle;
  margin-left: 8px; /* Adjust the margin as needed */
}

/* Bold style for user text */
.image_history + div b {
  font-weight: bold;
}
.image_profile {
  width: 64px;
  height: 64px;
  overflow: hidden;
  display: inline-block;
  position: relative;
}

.image_profile img {
  width: 100%;
  height: 100%;
  object-fit: cover; /* This property ensures the image fills the 32x32 container without distorting its aspect ratio */
  transform: scale(
    1
  ); /* Scale the image down to fit within the 32x32 container */
}
</style>
